sudo: false
language: node_js
node_js: 20

cache:
    directories:
        - ~/.npm
        - ~/.cache

notifications:
    email: false

jobs:
    include:
        - stage: test
          script:
              - npm run test
        - stage: release
          node_js: lts/*
          script:
              - yarn run test:coverage:coveralls
          deploy:
              provider: script
              skip_cleanup: true
              script: yarn release
